IsTrustedSequencer = true

[Log]
Environment = "development" # "production" or "development"
Level = "debug"
Outputs = ["stderr"]

[StateDB]
User = "state_user"
Password = "state_password"
Name = "state_db"
Host = "x1-state-db"
Port = "5432"
EnableLog = false
MaxConns = 200

[Pool]
FreeClaimGasLimit = 1500000
IntervalToRefreshBlockedAddresses = "5m"
IntervalToRefreshGasPrices = "5s"
MaxTxBytesSize=100132
MaxTxDataBytesSize=100000
DefaultMinGasPriceAllowed = 1000000000
MinAllowedGasPriceInterval = "5m"
PollMinAllowedGasPriceInterval = "15s"
FreeGasAddress = "0xf9c5135f7601F55414533c50366F8254A42204bC"
	[Pool.DB]
	User = "pool_user"
	Password = "pool_password"
	Name = "pool_db"
	Host = "x1-pool-db"
	Port = "5432"
	EnableLog = false
	MaxConns = 200

[Etherman]
URL = "https://fullnode.okg.com/sepolia/native/lightanalysis/rpc"
ForkIDChunkSize = 20000
MultiGasProvider = false
	[Etherscan]
		ApiKey = ""

[RPC]
Host = "0.0.0.0"
Port = 8123
ReadTimeout = "60s"
WriteTimeout = "60s"
MaxRequestsPerIPAndSecond = 5000
SequencerNodeURI = ""
EnableL2SuggestedGasPricePolling = true
	[RPC.WebSockets]
		Enabled = true
		Port = 8133

[Synchronizer]
SyncInterval = "1s"
SyncChunkSize = 100
TrustedSequencerURL = "" # If it is empty or not specified, then the value is read from the smc.

[Sequencer]
WaitPeriodPoolIsEmpty = "1s"
LastBatchVirtualizationTimeMaxWaitPeriod = "10s"
BlocksAmountForTxsToBeDeleted = 100
FrequencyToCheckTxsForDelete = "12h"
MaxTxsPerBatch = 300
MaxBatchBytesSize = 120000
MaxCumulativeGasUsed = 30000000
MaxKeccakHashes = 2145
MaxPoseidonHashes = 252357
MaxPoseidonPaddings = 135191
MaxMemAligns = 236585
MaxArithmetics = 236585
MaxBinaries = 473170
MaxSteps = 7570538
TxLifetimeCheckTimeout = "10m"
MaxTxLifetime = "3h"
	[Sequencer.Finalizer]
		GERDeadlineTimeout = "2s"
		ForcedBatchDeadlineTimeout = "5s"
		SleepDuration = "100ms"
		ResourcePercentageToCloseBatch = 10
		GERFinalityNumberOfBlocks = 0
		ClosingSignalsManagerWaitForCheckingL1Timeout = "10s"
		ClosingSignalsManagerWaitForCheckingGER = "10s"
		ClosingSignalsManagerWaitForCheckingForcedBatches = "10s"
		ForcedBatchesFinalityNumberOfBlocks = 0
		TimestampResolution = "2m"
		StopSequencerOnBatchNum = 211
	[Sequencer.DBManager]
		PoolRetrievalInterval = "500ms"
		L2ReorgRetrievalInterval = "5s"
	[Sequencer.EffectiveGasPrice]
		MaxBreakEvenGasPriceDeviationPercentage = 10
		L1GasPriceFactor = 0.25
		ByteGasCost = 16
		MarginFactor = 1
		Enabled = false

[SequenceSender]
WaitPeriodSendSequence = "15s"
LastBatchVirtualizationTimeMaxWaitPeriod = "10s"
MaxTxSizeForL1 = 131072
MaxBatchesForL1 = 10
SenderAddress = "0xb7cc460A2EC68fefe08d360069a52940a162eb02"
L2Coinbase = "0xb7cc460A2EC68fefe08d360069a52940a162eb02"
#SenderAddress = "0x1A13bDDCC02D363366E04D4aA588d3C125B0Ff6F"
#L2Coinbase = "0x1A13bDDCC02D363366E04D4aA588d3C125B0Ff6F"
#SenderAddress = "0xA62227E0D41E6B2fc4A6083866ee6Ee6c67D9e8f"
#L2Coinbase = "0xA62227E0D41E6B2fc4A6083866ee6Ee6c67D9e8f"
PrivateKey = {Path = "/pk/sequencer.keystore", Password = "password"}
DAPermitApiPrivateKey = {Path = "/pk/da-signer.keystore", Password = "password"}
UseValidium = true

[Aggregator]
Host = "0.0.0.0"
Port = 50081
RetryTime = "5s"
VerifyProofInterval = "10s"
TxProfitabilityCheckerType = "acceptall"
TxProfitabilityMinReward = "1.1"
ProofStatePollingInterval = "5s"
SenderAddress = "0xF83c964723a1065e0b3509Fc5536Ef3F1aF123A6"
#SenderAddress = "0x66e39A1E507Af777E8c385E2d91559e20E306303"
#SenderAddress = "0x956716e4eE093EA7658e784b2FF4FD3877E7e7c0"
CleanupLockedProofsInterval = "2m"
GeneratingProofCleanupThreshold = "10m"

[EthTxManager]
ForcedGas = 0
PrivateKeys = [
	{Path = "/pk/sequencer.keystore", Password = "password"},
	{Path = "/pk/aggregator.keystore", Password = "password"}
]
	[EthTxManager.CustodialAssets]
		Enable=false
		URL="https://test-x1asset.okg.com"
		#URL="http://52.40.99.48:4001"
		Symbol=2882
		SequencerAddr="0x1A13bDDCC02D363366E04D4aA588d3C125B0Ff6F"
		AggregatorAddr="0x66e39A1E507Af777E8c385E2d91559e20E306303"
		WaitResultTimeout="2m"

[L2GasPriceSuggester]
Type = "default"
UpdatePeriod = "10s"
Factor = 0.5
DefaultGasPriceWei = 1000000000
MaxGasPriceWei = 0

[MTClient]
URI  = "x1-prover:50061"

[Executor]
URI = "x1-prover:50071"
MaxGRPCMessageSize = 100000000

[Metrics]
Host = "0.0.0.0"
Port = 9091
Enabled = true
ProfilingHost = "0.0.0.0"
ProfilingPort = 6060
ProfilingEnabled = true

[EventLog]
	[EventLog.DB]
	User = "event_user"
	Password = "event_password"
	Name = "event_db"
	Host = "x1-event-db"
	Port = "5432"
	EnableLog = false
	MaxConns = 200

[HashDB]
User = "prover_user"
Password = "prover_pass"
Name = "prover_db"
Host = "x1-state-db"
Port = "5432"
EnableLog = false
MaxConns = 200
