PrivateKey = {Path = "/pk/test-member.keystore", Password = "password"}
PermitApiAddress = "0x10e74D2F5af249e1f212C8653F82793B922b3946"

[L1]
WsURL = "wss://sepolia.infura.io/ws/v3/0d081e04621c4c69b12649fbb63ef18a"
RpcURL = "https://fullnode.okg.com/sepolia/native/lightanalysis/rpc"
ZkEVMAddress = "0x8288042CDcFf6C1F158D3bc357fF2ffF4e959E28"
DataCommitteeAddress = "0x4eFc42f0C5c6c457E022E945EEB157d185534e9C"
Timeout = "3m"
RetryPeriod = "5s"

[Log]
Environment = "development" # "production" or "development"
Level = "debug"
Outputs = ["stderr"]

[DB]
User = "committee_user"
Password = "committee_password"
Name = "committee_db"
Host = "x1-data-availability-db"
Port = "5432"
EnableLog = false
MaxConns = 200

[RPC]
Host = "0.0.0.0"
Port = 8444
ReadTimeout = "60s"
WriteTimeout = "60s"
MaxRequestsPerIPAndSecond = 500
SequencerNodeURI = ""
EnableL2SuggestedGasPricePolling = false
	[RPC.WebSockets]
		Enabled = false
